### ISSUE TITLE
Docker image to build the entire repository

### ISSUE THREAD

**Issue by Diptonil** [Diptonil/raging-coffee#12]
A Dockerfile needs to be created that:
- Copies all the source files into the working directory.
- Built atop Maven supporting JDK.
- Contributors with basic knowledge of Docker can try to contribute. Image validating the following would be considered as proof for resolution of the issue:
  - Correct running of any program inside a Docker container.
  - Correct running of all tests inside a Docker container upon running `mvn test`.

Modify the Dockerfile inside the `.devcontainer` to complete the task.

**Comment by Diptonil** [comment]
Sure. If you're confident with Docker, you can go ahead. I'll assign you this issue. Just let me have the images for proof after you're done with the work.

**Comment by jivjen** [comment]
@Diptonil I've raised the below PR.
Could you please check?
https://github.com/Diptonil/raging-coffee/pull/17

**Comment by Diptonil** [comment]
Sure. The PR looks neat. I'll get back to you within a few hours.

**Comment by Diptonil** [comment]
Issue has been resolved.
