### ISSUE TITLE
Faulty random number generator in caching section

### ISSUE THREAD

**Issue by Diptonil** [Diptonil/raging-coffee#14]
- The random number generator in caching section is required to give umbers from 0 to 19. It currently given numbers from 1 to 20. This needs to be fixed.
- Optional: A mechanism to ensure that the random number generated is not the same that was generated before in the cache data structure.

To understand more, take a close look at the `cachingalgorithms` section.

**Comment by jivjen** [comment]
Hi @Diptonil 
Can I please take this up?
